version: '3.8'
services:
    deluge:
        container_name: deluge
        image: 'linuxserver/deluge:latest'
        restart: unless-stopped
        network_mode: host
        environment:
            - 'PUID=${PUID}'
            - 'PGID=${PGID}'
            - 'TZ=${TZ}'
        volumes:
            - '${ROOT}/downloads:/downloads'
            - '${ROOT}/config/deluge:/config'
        labels:
            - 'name="Deluge"'
            - 'description="Deluge Torrent Client"'
            - 'department="Media"'

    jackett:
        container_name: jackett
        image: 'linuxserver/jackett:latest'
        restart: unless-stopped
        ports:
            - '9117:9117'
        environment:
            - 'PUID=${PUID}'
            - 'PGID=${PGID}'
            - 'TZ=${TZ}'
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '${ROOT}/downloads/torrent-blackhole:/downloads'
            - '${ROOT}/config/jackett:/config'
        labels:
            - 'name="Jackett"'
            - 'description="Jackett Torrent Indexer"'
            - 'department="Media"'

    nzbget:
        container_name: nzbget
        image: 'linuxserver/nzbget:latest'
        restart: unless-stopped
        network_mode: host
        environment:
            - 'PUID=${PUID}'
            - 'PGID=${PGID}'
            - 'TZ=${TZ}'
        volumes:
            - '${ROOT}/downloads:/downloads'
            - '${ROOT}/config:/config'
        labels:
            - 'name="NZBGet"'
            - 'description="NZBGet Usenet Downloader"'
            - 'department="Media"'

    sonarr:
        container_name: sonarr
        image: 'linuxserver/sonarr:preview'
        restart: unless-stopped
        ports:
            - '8989:8989'
        environment:
            - 'PUID=${PUID}'
            - 'PGID=${PGID}'
            - 'TZ=${TZ}'
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '${ROOT}/config/sonarr:/config'
            - '${ROOT}/complete/tv://tv'
            - '${ROOT}/downloads:/downloads'
        labels:
            - 'name="Sonarr"'
            - 'description="Sonarr TV Show Downloader"'
            - 'department="Media"'

    radarr:
        container_name: radarr
        image: 'linuxserver/radarr:latest'
        restart: unless-stopped
        ports:
            - '7878:7878'
        environment:
            - 'PUID=${PUID}'
            - 'PGID=${PGID}'
            - 'TZ=${TZ}'
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '${ROOT}/config/radarr:/config'
            - '${ROOT}/complete/movies:/movies'
            - '${ROOT}/downloads:/downloads'
        labels:
            - 'name="Radarr"'
            - 'description="Radarr Movie Downloader"'
            - 'department="Media"'

    lidarr:
        image: linuxserver/lidarr:latest
        container_name: lidarr
        restart: unless-stopped
        ports:
            - '8686:8686'

        environment:
            - 'PUID=${PUID}'
            - 'PGID=${PGID}'
            - 'TZ=${TZ}'
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '${ROOT}/config/lidarr:/config'
            - '${ROOT}/complete/music:/music'
            - '${ROOT}/downloads/complete:/downloads'
        labels:
            - 'name="Lidarr"'
            - 'description="Lidarr Music Downloader"'
            - 'department="Media"'

    bazarr:
        container_name: bazarr
        image: linuxserver/bazarr:latest
        restart: unless-stopped
        network_mode: host
        environment:
            - 'PUID=${PUID}'
            - 'PGID=${PGID}'
            - 'TZ=${TZ}'
            - UMASK_SET=022
        volumes:
            - '${ROOT}/config/bazarr:/config'
            - '${ROOT}/complete/movies:/movies'
            - '${ROOT}/complete/tv:/tv'
        labels:
            - 'name="Bazarr"'
            - 'description="Bazarr Subtitle Downloader"'
            - 'department="Media"'

    plex:
        container_name: plex
        image: 'plexinc/pms-docker:latest'
        restart: unless-stopped
        environment:
            - 'PLEX_UID=${PUID}'
            - 'PLEX_GID=${PGID}'
            - 'TZ=${TZ}'
            - 'PLEX_CLAIM=${PLEX_CLAIM}'
        ports:
            - '32400:32400'
            - '3005:3005'
            - '8324:8324'
            - '32469:32469'
            - '1900:1900'
            - '32410:32410'
            - '32412:32412'
            - '32413:32413'
            - '32414:32414'
        volumes:
            - '${ROOT}/config/plex/db:/config'
            - '${ROOT}/config/plex/transcode:/transcode'
            - '${ROOT}/complete:/data'
        labels:
            - 'name="Plex"'
            - 'description="Plex Media Server"'
            - 'department="Media"'

    tautulli:
        image: linuxserver/tautulli:latest
        container_name: tautulli
        restart: unless-stopped
        environment:
            - 'PUID=${PUID}'
            - 'PGID=${PGID}'
            - 'TZ=${TZ}'
        volumes:
            - '${ROOT}/config/tautulli:/config'
        ports:
            - '8063:8181'
        labels:
            - 'name="Tautulli"'
            - 'description="Tautulli Plex Monitoring"'
            - 'department="Media"'

    jellyfin:
        image: linuxserver/jellyfin:latest
        container_name: jellyfin
        restart: unless-stopped
        ports:
            - '8096:8096'
            - '8920:8920'
        environment:
            - 'PUID=${PUID}'
            - 'PGID=${PGID}'
            - 'TZ=${TZ}'
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '${ROOT}/config/jellyfin:/config'
            - '${ROOT}/complete/tv:/data/tvshows'
            - '${ROOT}/complete/movies:/data/movies'
            - '${ROOT}/complete/music:/data/music'
            - '/opt/vc/lib:/opt/vc/lib'
        labels:
            - 'name="Jellyfin"'
            - 'description="Jellyfin Media Server"'
            - 'department="Media"'

    couchpotato:
        image: linuxserver/couchpotato:latest
        container_name: couchpotato
        restart: unless-stopped
        ports:
            - '5050:5050'
        environment:
            - 'PUID=${PUID}'
            - 'PGID=${PGID}'
            - 'TZ=${TZ}'
        volumes:
            - '${ROOT}/config/couchpotato/config:/config'
            - '${ROOT}/downloads:/downloads'
            - '${ROOT}/complete/movies:/movies'
        labels:
            - 'name="CouchPotato"'
            - 'description="CouchPotato Movie Downloader"'
            - 'department="Media"'

    ombi:
        image: linuxserver/ombi:latest
        container_name: ombi
        restart: unless-stopped
        environment:
            - 'PUID=${PUID}'
            - 'PGID=${PGID}'
            - 'TZ=${TZ}'
        volumes:
            - '${ROOT}/config/ombi/config:/config'
        ports:
            - '3579:3579'
        labels:
            - 'name="Ombi"'
            - 'description="Ombi Media Request System"'
            - 'department="Media"'

    netdata:
        image: netdata/netdata:latest
        container_name: netdata
        restart: unless-stopped
        environment:
            - 'PUID=${PUID}'
            - 'PGID=${PGID}'
            - 'TZ=${TZ}'
        ports:
            - '19999:19999'
        cap_add:
            - SYS_PTRACE
        security_opt:
            - 'apparmor:unconfined'
        volumes:
            - '/etc/passwd:/host/etc/passwd:ro'
            - '/etc/group:/host/etc/group:ro'
            - '/proc:/host/proc:ro'
            - '/sys:/host/sys:ro'
        labels:
            - 'name="Netdata"'
            - 'description="Netdata System Monitoring"'
            - 'department="System"'

    dashmachine:
        image: "rmountjoy/dashmachine:latest"
        container_name: dashmachine
        restart: unless-stopped
        environment:
            - PUID='${PUID}'
            - PGID='${PGID}'
            - TZ='${TZ}'
        ports:
            - "5000:5000"
        volumes:
            - "${ROOT}/config/dashmachine:/dashmachine/dashmachine/user_data"
        labels:
            - 'name="Dashmachine"'
            - 'description="Dashmachine Dashboard"'
            - 'department="System"'

    filebrowser:
        image: filebrowser/filebrowser:latest
        container_name: filebrowser
        restart: unless-stopped
        environment:
            - PUID='${PUID}'
            - PGID='${PGID}'
            - TZ='${TZ}'
        volumes:
            - '${ROOT}/config/filebrowser/database.db:/database.db'
            - '${ROOT}:/srv'
        ports:
            - '8999:80'
        labels:
            - 'name="Filebrowser"'
            - 'description="Filebrowser File Manager"'
            - 'department="System"'

    hydra2:
        image: linuxserver/hydra2:latest
        container_name: hydra2
        restart: unless-stopped
        environment:
            - PUID='${PUID}'
            - PGID='${PGID}'
            - TZ='${TZ}'
        volumes:
            - '${ROOT}/config/hydra2:/config'
            - '${ROOT}/downloads:/downloads'
        ports:
            - 5076:5076

        labels:
            - 'name="Hydra2"'
            - 'description="Hydra2 NZB Indexer"'
            - 'department="Media"'

    tdarr:
        image: haveagitgat/tdarr_aio
        container_name: tdarr
        restart: unless-stopped
        ports:
            - '8265:8265'
        environment:
            - PUID='${PUID}'
            - PGID='${PGID}'
            - TZ='${TZ}'
        volumes:
            - '${ROOT}/complete:/home/Tdarr/Media'
            - '${ROOT}/config/tdarr:/home/Tdarr/Documents/Tdarr'
            - '${ROOT}/config/tdarr/db:/var/lib/mongodb'
            - '/etc/localtime:/etc/localtime:ro'
        labels:
            - 'name="Tdarr"'
            - 'description="Tdarr Media Converter"'
            - 'department="Media"'

    prowlarr:
        container_name: prowlarr
        image: 'hotio/prowlarr'
        restart: unless-stopped
        ports:
            - '9696:9696'
        environment:
            - 'PUID=${PUID}'
            - 'PGID=${PGID}'
            - 'TZ=${TZ}'
        volumes:
            - '${ROOT}/config/prowlarr:/config'
            - '${ROOT}/downloads:/downloads'
        labels:
            - 'name="Prowlarr"'
            - 'description="Prowlarr Unified Indexer"'
            - 'department="Media"'

    readarr:
        container_name: readarr
        image: 'hotio/readarr'
        restart: unless-stopped
        ports:
            - '8787:8787'
        environment:
            - 'PUID=${PUID}'
            - 'PGID=${PGID}'
            - 'TZ=${TZ}'
        volumes:
            - '${ROOT}/config/readarr:/config'
            - '${ROOT}/complete/books:/books'
        labels:
            - 'name="Readarr"'
            - 'description="Readarr Book Management"'
            - 'department="Media"'
    whisparr:
        container_name: whisparr
        image: 'ghcr.io/hotio/whisparr'
        restart: unless-stopped
        ports:
            - '6969:6969'
        environment:
            - 'PUID=${PUID}'
            - 'PGID=${PGID}'
            - 'TZ=${TZ}'
        volumes:
            - '${ROOT}/config/whisparr:/config'
            - '${ROOT}/downloads:/downloads'
        labels:
            - 'name="Whisparr"'
            - 'description="Whisparr Media Management"'
            - 'department="Media"'

    stash:
        container_name: stash
        image: 'hotio/stash'
        restart: unless-stopped
        ports:
            - '9999:9999'
        environment:
            - 'PUID=${PUID}'
            - 'PGID=${PGID}'
            - 'TZ=${TZ}'
        volumes:
            - '${ROOT}/config/stash:/config'
            - '${ROOT}/complete/adult:/adult'
        labels:
            - 'name="Stash"'
            - 'description="Stash Adult Media Organizer"'
            - 'department="Media"'

    jellyseerr:
        container_name: jellyseerr
        image: 'hotio/jellyseerr'
        restart: unless-stopped
        ports:
            - '8097:8097'
        environment:
            - 'PUID=${PUID}'
            - 'PGID=${PGID}'
            - 'TZ=${TZ}'
        volumes:
            - '${ROOT}/config/jellyseerr:/config'
            - '${ROOT}/complete:/complete'
        labels:
            - 'name="Jellyseerr"'
            - 'description="Jellyseerr Media Server"'
            - 'department="Media"'
