version: '3.7'
services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    ports:
      - '9000:9000'
      - '8000:8000'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/home/antoine/portainer:/data'
    restart: always
