version: "3.7"
services:
  wg-access-server:
    image: place1/wg-access-server
    container_name: wg-access-server
    cap_add:
      - NET_ADMIN
    volumes:
      - "./data:/data"
      - "./config.yaml:/config.yaml" # if you have a custom config file
    ports:
      - "8000:8000/tcp"
      - "51820:51820/udp"
    devices:
      - "/dev/net/tun:/dev/net/tun"
    restart: unless-stopped
    labels:
      - "name=wg-access-server"
      - "description=WireGuard Access Server"
      - "department=IT"